version: "3.8"
services:
  ioc:
    image: ghcr.io/lnls-dig/sinap-timing-epics-ioc:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/Dockerfile
      labels:
        org.opencontainers.image.revision: ${COMMIT_ID}
        org.opencontainers.image.source: https://github.com/lnls-dig/sinap-timing-epics-ioc
        org.opencontainers.image.description: "SINAP Timing EPICS IOC container"
      args:
        REPONAME: sinap-timing-epics-ioc
        RUNDIR: /opt/sinap-timing-epics-ioc/iocBoot/ioctiming
        ENTRYPOINT: ./runProcServ.sh
        RUNTIME_PACKAGES: python3-minimal libpython3-stdlib ca-certificates
