#############################################################################
##### This file content is automatically generated by ./event_alias.py  #####
#####    at IOC startup based on High-Level Events                      #####
#####                                                                   #####
#####                      DO NOT DELETE OR MODIFY IT                   #####
#############################################################################
