seq EVGFOUTRxLocked, "P=${P}, R=${R}, num=0"
seq EVGFOUTRxLocked, "P=${P}, R=${R}, num=1"
seq EVGFOUTRxLocked, "P=${P}, R=${R}, num=2"
seq EVGFOUTRxLocked, "P=${P}, R=${R}, num=3"
seq EVGFOUTRxLocked, "P=${P}, R=${R}, num=4"
seq EVGFOUTRxLocked, "P=${P}, R=${R}, num=5"
seq EVGFOUTRxLocked, "P=${P}, R=${R}, num=6"
seq EVGFOUTRxLocked, "P=${P}, R=${R}, num=7"
