/* C code for program sncModuleSupport, generated by snc from ./../sncModuleSupport.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"

/* Variable declarations */
# line 3 "./../sncModuleSupport.stt"
static	int uploadproc;
# line 6 "./../sncModuleSupport.stt"
static	int downloadproc;
# line 9 "./../sncModuleSupport.stt"
static	int download;
# line 13 "./../sncModuleSupport.stt"
static	int statdev;
# line 17 "./../sncModuleSupport.stt"
static	int past_alive;
# line 18 "./../sncModuleSupport.stt"
static	int alive;
# line 22 "./../sncModuleSupport.stt"
static	int funselRBV;
# line 26 "./../sncModuleSupport.stt"
static	int network;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 17 "./../sncModuleSupport.stt"
	static int seqg_initvar_past_alive = -1;
	memcpy(&past_alive, &seqg_initvar_past_alive, sizeof(seqg_initvar_past_alive));
	}
}

/****** Code for state "init" in state set "configuration" ******/

/* Event function for state "init" in state set "configuration" */
static seqBool seqg_event_configuration_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 31 "./../sncModuleSupport.stt"
	if (seq_delay(seqg_env, 1.0))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "configuration" */
static void seqg_action_configuration_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 32 "./../sncModuleSupport.stt"
			printf("\n%s state machine initiated\n", seq_macValueGet(seqg_env, "device"));
		}
		return;
	}
}

/****** Code for state "upload" in state set "configuration" ******/

/* Event function for state "upload" in state set "configuration" */
static seqBool seqg_event_configuration_0_upload(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 36 "./../sncModuleSupport.stt"
	if (statdev == 0)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 38 "./../sncModuleSupport.stt"
	if (network == 1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 43 "./../sncModuleSupport.stt"
	if (seq_delay(seqg_env, 2.0))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "upload" in state set "configuration" */
static void seqg_action_configuration_0_upload(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 39 "./../sncModuleSupport.stt"
			uploadproc = 1;
# line 40 "./../sncModuleSupport.stt"
			seq_pvPutTmo(seqg_env, 0/*uploadproc*/, SYNC, DEFAULT_TIMEOUT);
# line 41 "./../sncModuleSupport.stt"
			printf("\nConfiguration uploaded from %s.\n", seq_macValueGet(seqg_env, "device"));
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "waiting" in state set "configuration" ******/

/* Event function for state "waiting" in state set "configuration" */
static seqBool seqg_event_configuration_0_waiting(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 47 "./../sncModuleSupport.stt"
	if ((statdev == 0) && (network == 1))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 50 "./../sncModuleSupport.stt"
	if ((download == 1) && (network == 1))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 53 "./../sncModuleSupport.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "waiting" in state set "configuration" */
static void seqg_action_configuration_0_waiting(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 48 "./../sncModuleSupport.stt"
			download = 1;
		}
		return;
	case 1:
		{
# line 51 "./../sncModuleSupport.stt"
			download = 1;
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "download" in state set "configuration" ******/

/* Entry function for state "download" in state set "configuration" */
static void seqg_entry_configuration_0_download(SS_ID seqg_env)
{
# line 59 "./../sncModuleSupport.stt"
	downloadproc = 1;
# line 60 "./../sncModuleSupport.stt"
	seq_pvPutTmo(seqg_env, 1/*downloadproc*/, SYNC, DEFAULT_TIMEOUT);
# line 61 "./../sncModuleSupport.stt"
	printf("\nConfiguration downloaded to %s.\n", seq_macValueGet(seqg_env, "device"));
# line 62 "./../sncModuleSupport.stt"
	download = 0;
# line 63 "./../sncModuleSupport.stt"
	seq_pvPutTmo(seqg_env, 2/*download*/, SYNC, DEFAULT_TIMEOUT);
}

/* Event function for state "download" in state set "configuration" */
static seqBool seqg_event_configuration_0_download(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 65 "./../sncModuleSupport.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "download" in state set "configuration" */
static void seqg_action_configuration_0_download(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "networkCheck" in state set "networkStatus" ******/

/* Event function for state "networkCheck" in state set "networkStatus" */
static seqBool seqg_event_networkStatus_1_networkCheck(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 72 "./../sncModuleSupport.stt"
	if (seq_delay(seqg_env, 2.0))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "networkCheck" in state set "networkStatus" */
static void seqg_action_networkStatus_1_networkCheck(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 73 "./../sncModuleSupport.stt"
			if (funselRBV == 0)
			{
# line 74 "./../sncModuleSupport.stt"
				past_alive = -1;
# line 75 "./../sncModuleSupport.stt"
				network = 0;
# line 76 "./../sncModuleSupport.stt"
				seq_pvPutTmo(seqg_env, 6/*network*/, SYNC, DEFAULT_TIMEOUT);
			}
			else
# line 78 "./../sncModuleSupport.stt"
				if (statdev == 0)
				{
# line 79 "./../sncModuleSupport.stt"
					past_alive = -1;
# line 80 "./../sncModuleSupport.stt"
					network = 1;
# line 81 "./../sncModuleSupport.stt"
					seq_pvPutTmo(seqg_env, 6/*network*/, SYNC, DEFAULT_TIMEOUT);
				}
				else
# line 83 "./../sncModuleSupport.stt"
					if (alive > past_alive)
					{
# line 84 "./../sncModuleSupport.stt"
						past_alive = alive;
# line 85 "./../sncModuleSupport.stt"
						network = 1;
# line 86 "./../sncModuleSupport.stt"
						seq_pvPutTmo(seqg_env, 6/*network*/, SYNC, DEFAULT_TIMEOUT);
					}
					else
					{
# line 89 "./../sncModuleSupport.stt"
						past_alive = alive;
# line 90 "./../sncModuleSupport.stt"
						network = 0;
# line 91 "./../sncModuleSupport.stt"
						seq_pvPutTmo(seqg_env, 6/*network*/, SYNC, DEFAULT_TIMEOUT);
					}
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{device}:uploadT.PROC", (size_t)&uploadproc, "uploadproc", P_INT, 1, 1, 0, 0, 0, 0},
	{"{device}:downloadT.PROC", (size_t)&downloadproc, "downloadproc", P_INT, 1, 2, 0, 0, 0, 0},
	{"{device}:download.VAL", (size_t)&download, "download", P_INT, 1, 3, 0, 1, 0, 0},
	{"{device}:statdev", (size_t)&statdev, "statdev", P_INT, 1, 4, 0, 1, 0, 0},
	{"{device}:alive", (size_t)&alive, "alive", P_INT, 1, 5, 0, 1, 0, 0},
	{"{device}:funselRBV", (size_t)&funselRBV, "funselRBV", P_INT, 1, 6, 0, 1, 0, 0},
	{"{device}:network", (size_t)&network, "network", P_INT, 1, 7, 0, 0, 0, 0},
};

/* Event masks for state set "configuration" */
static const seqMask seqg_mask_configuration_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_configuration_0_upload[] = {
	0x00000090,
};
static const seqMask seqg_mask_configuration_0_waiting[] = {
	0x00000098,
};
static const seqMask seqg_mask_configuration_0_download[] = {
	0x00000000,
};

/* State table for state set "configuration" */
static seqState seqg_states_configuration[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_configuration_0_init,
	/* event function */    seqg_event_configuration_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_configuration_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "upload",
	/* action function */   seqg_action_configuration_0_upload,
	/* event function */    seqg_event_configuration_0_upload,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_configuration_0_upload,
	/* state options */     (0)
	},
	{
	/* state name */        "waiting",
	/* action function */   seqg_action_configuration_0_waiting,
	/* event function */    seqg_event_configuration_0_waiting,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_configuration_0_waiting,
	/* state options */     (0)
	},
	{
	/* state name */        "download",
	/* action function */   seqg_action_configuration_0_download,
	/* event function */    seqg_event_configuration_0_download,
	/* entry function */    seqg_entry_configuration_0_download,
	/* exit function */     0,
	/* event mask array */  seqg_mask_configuration_0_download,
	/* state options */     (0)
	},
};

/* Event masks for state set "networkStatus" */
static const seqMask seqg_mask_networkStatus_1_networkCheck[] = {
	0x00000000,
};

/* State table for state set "networkStatus" */
static seqState seqg_states_networkStatus[] = {
	{
	/* state name */        "networkCheck",
	/* action function */   seqg_action_networkStatus_1_networkCheck,
	/* event function */    seqg_event_networkStatus_1_networkCheck,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_networkStatus_1_networkCheck,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "configuration",
	/* states */            seqg_states_configuration,
	/* number of states */  4
	},

	{
	/* state set name */    "networkStatus",
	/* states */            seqg_states_networkStatus,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram sncModuleSupport = {
	/* magic number */      2002001,
	/* program name */      "sncModuleSupport",
	/* channels */          seqg_chans,
	/* num. channels */     7,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define PROG_NAME sncModuleSupport
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void sncModuleSupportRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&sncModuleSupport);
}
epicsExportRegistrar(sncModuleSupportRegistrar);
